# Models to train and their hyperparameters
models:
  random_forest:
    enabled: true
    params:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
    hyperparameter_tuning:
      enabled: false
      param_grid:
        n_estimators: [50, 100, 200]
        max_depth: [5, 10, 15, 20, null]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
  
  xgboost:
    enabled: true
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 5
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
    hyperparameter_tuning:
      enabled: false
      param_grid:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.05, 0.1]
        max_depth: [3, 5, 7]
        subsample: [0.7, 0.8, 0.9]
        colsample_bytree: [0.7, 0.8, 0.9]

  MLP:
    enabled: false
    params:
      hidden_layer_sizes: [100, 50]
      activation: relu
      solver: adam
      learning_rate: adaptive
      max_iter: 1000
      alpha: 0.0001
      random_state: 42
    hyperparameter_tuning:
      enabled: false
      param_grid:
        hidden_layer_sizes: [[50], [100], [50, 50], [100, 50]]
        activation: [relu, tanh]
        alpha: [0.0001, 0.001, 0.01]
        learning_rate: [constant, adaptive]
        max_iter: [500, 1000, 2000]

# Cross-validation settings
cross_validation:
  enabled: true
  cv: 5
  scoring: 'neg_mean_squared_error'
  random_state: 42

# Model evaluation metrics for classification problem
evaluation:
  showall: true  # Show all metrics
  metrics:
    - accuracy
    - precision
    - recall
    - f1
