# Data preprocessing configuration

# Columns information
columns: 
  categorical: # Columns to encode
    - System Location Code
    - Previous Cycle Plant Type
    - Plant Type
    - Plant Stage
    - Plant Type-Stage
  
  numerical:
    - Temperature Sensor (째C)
    - Humidity Sensor (%)
    - Light Intensity Sensor (lux)
    - CO2 Sensor (ppm)
    - EC Sensor (dS/m)
    - O2 Sensor (ppm)
    - Nutrient N Sensor (ppm) # clean_Nutrient_Sensor has to be enabled
    - Nutrient P Sensor (ppm) # clean_Nutrient_Sensor has to be enabled
    - Nutrient K Sensor (ppm) # clean_Nutrient_Sensor has to be enabled
    - pH Sensor
    - Water Level Sensor (mm)
  
  datetime:
    - sleep_time
    - wake_time
  
  drop_columns: # Columns to drop from the dataset manually e.g. none
    - System Location Code
 

# Data cleaning settings
cleaning:
  clean_Nutrient_Sensor:
    enabled: true
    columns:
      - Nutrient N Sensor (ppm)
      - Nutrient P Sensor (ppm)
      - Nutrient K Sensor (ppm)
      
  handle_negative_values:
    enabled: true
    columns:
      - Temperature Sensor (째C)
      - Light Intensity Sensor (lux)
    strategy: absolute  # Options: remove, absolute
  
  map_labels_to_lowercase:
    enabled: true
    columns:
      - Plant Type 
      - Plant Stage
  
  handle_duplicates:
    enabled: true
    ignore_columns:
      none
    keep: first
  
  handle_missing_values:
    enabled: true
    numerical:
      strategy: median  # Options: mean, median, mode, constant
      constant_value: 0  # Only used if strategy is constant
    
    categorical:
      strategy: mode  # Options: mode, constant
      constant_value: "unknown"  # Only used if strategy is constant
  
  handle_outliers:
    enabled: false 
    method: iqr  # Options: iqr, zscore, none
    iqr_multiplier: 1.5
    zscore_threshold: 3.0
    columns:
      - age
      - hours_per_week
      - attendance_rate
      - Temperature Sensor (째C)
      - Humidity Sensor (%)
      - Light Intensity Sensor (lux)
      - CO2 Sensor (ppm)
      - EC Sensor (dS/m)
      - O2 Sensor (ppm)
      - Nutrient N Sensor (ppm)
      - Nutrient P Sensor (ppm)
      - Nutrient K Sensor (ppm)
      - pH Sensor
      - Water Level Sensor (mm)

# Feature preprocessing
preprocessing:
  categorical_encoding:
    method: one-hot  # Options: one-hot, label, target, frequency
    handle_unknown: ignore
    
  numerical_scaling:
    method: standard  # Options: standard, minmax, robust, none

# Feature engineering
feature_engineering:
  create_nutrient_balance_index:
    enabled: true
    from_columns:
      - Nutrient N Sensor (ppm)
      - Nutrient P Sensor (ppm)
      - Nutrient K Sensor (ppm)

  create_environmental_stress_index:
    enabled: true
    from_columns:
      - Temperature Sensor (째C)
      - Humidity Sensor (%)
      - Light Intensity Sensor (lux)
      - CO2 Sensor (ppm)
      - O2 Sensor (ppm)

  create_water_quality_score:
    enabled: true
    from_columns:
      - pH Sensor
      - EC Sensor (dS/m)
      - Water Level Sensor (mm)

  delete_Type_Stage_AfterCombination: # Delete the columns used to create the new feature "Plant Type-Stage"
    enabled: true

# Feature selection
feature_selection:
  method: none  # Options: variance, correlation, importance, none
  variance_threshold: 0.01  # Only used if method is variance
  correlation_threshold: 0.8  # Only used if method is correlation
