# Data CLEANING and PREPROCESSING configuration

#--------------------------------Columns information-------------------------------#
columns: # Columns not defined these lists will be removed
  others:
    - Subscription Status  # Target variable
    # - Client ID  # Unique identifier, not useful for modeling
  categorical:
    Ordinal:
      - Education Level  # Has natural order from illiterate to university degree
    One-hot:
      - Occupation      # No inherent order
      - Credit Default  # Binary + unknown
      - Housing Loan    # Binary + unknown
      - Personal Loan   # Binary + unknown
      - Contact Method  # Distinct categories
      - Marital Status # Distinct categories
  numerical:
    # - Client ID # Unique identifier, not useful for modeling
    - Age
    - Campaign Calls
    - Previous Contact Days
 
#--------------------------------Data cleaning settings-----------------------------#
cleaning: 
  drop_columns: # Columns to drop from the dataset manually e.g. none
    enabled: true
    columns:
      # - Housing Loan # Contains the most number of NaN values

  handle_unknown_values: # Change values that are 'unknown' to NaN
    enabled: true
    columns: # List columns that have 'unknown' values
      - Occupation
      # - Marital Status
      - Education Level
      # - Credit Default
      - Housing Loan # Both Housing Loan and Personal Loan have existing NaN values
      - Personal Loan
    
  impute:
    enabled: true
    columns:
      - Occupation
      - Housing Loan
      - Education Level
      - Personal Loan
    strategy: mode  # Options: mode, constant, knn, random
    neighbors: 5  # Only used if strategy is knn
  
  handle_negative_values:
    enabled: true
    columns:
      - Campaign Calls
    strategy: absolute  # Options: remove, absolute

#-------------------------------Feature preprocessing settings--------------#
preprocessing:
  handle_outliers:
      enabled: false 
      method: iqr  # Options: iqr, zscore
      iqr_multiplier: 1.5
      zscore_threshold: 3.0
      columns:
        - Campaign Calls
        - Age
        # - Previous Contact Days #Do not include as data is bimodal
    
  numerical_scaling:
    method: standard  # Options: standard, minmax, robust, none
    columns:
      - Campaign Calls
      - Age
      # - Previous Contact Days #Do not include as data is bimodal

  # Feature selection
  feature_selection:
    method: none  # Options: variance, correlation, importance, none
    variance_threshold: 0.01  # Only used if method is variance
    correlation_threshold: 0.8  # Only used if method is correlation
